# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - pages/home.md
  - pages/contact.md

footer: '<a href="https://b2a3e8.github.io/jekyll-theme-console-demo-light/">light</a>'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
